meta_product_name: "TR - Portfolio"
meta_title: "Here is my portfolio - Thomas Rodier"
meta_description: "Want to do create a website ? We keep in touch"
meta_image: "meta-image.png" # should exist in `app/assets/images/`
twitter_account: "@rodiert17"   # required for Twitter Cards
